### ISSUE TITLE
How to link the polygon did to its ethereum address

### ISSUE THREAD

**Issue by hero5512** [0xPolygonID/issuer-node#417]
As I know polygon id generated by the genesis state, but the ethereum is generated by its public key. So how to link the ethereum address to its polygon id?

**Comment by Groovytent** [comment]
what is a goal? to derive identity from the Ethereum key? then you can derive BJJ private key from the Ethereum key as a seed so that the genesis state will be derived from the Ethereum key.
in future, it will be possible to create on-chain identities, so it will be possible to use the Ethereum address as a genesis identifier of identity.

**Comment by x1m3** [comment]
We release this feature some days ago https://devs.polygonid.com/docs/issuer/features/#did-with-ethereum-address
